model:
  name: "huggyllama/llama-7b"
  max_length: 80
  num_labels: null  # Will be set dynamically based on dataset
  problem_type: "multi_label_classification"

training:
  output_dir: "./results"
  evaluation_strategy: "epoch"
  per_device_train_batch_size: 8
  per_device_eval_batch_size: 8
  num_train_epochs: 3
  weight_decay: 0.01
  metric_for_best_model: "f1"
  load_best_model_at_end: true

data:
  raw_data_path: "data/raw/data.json"
  sample_data_path: "data/processed/sample_data.json"
  test_size: 0.2
  random_seed: 42

paths:
  results_dir: "./results"
  model_dir: "./results/model"
  tokenizer_dir: "./results/tokenizer" 